from __future__ import annotations


def _strategy(
    *,
    id: str,
    name: str,
    repo: str,
    category: str,
    purpose: str,
    hypothesis: str,
    status_state: str,
    status_pct: int,
    operational_status: str,
    verdict: str,
    tags: list[str],
    files: list[tuple[str, str, str]],
    components: list[tuple[str, str, str]],
    metrics: list[tuple[str, str, str]],
    watchlist: list[tuple[str, str, str, str]],
    notes: str = "",
    versions: list[dict] | None = None,
    shadow: bool = False,
) -> dict:
    return {
        "id": id,
        "name": name,
        "repo": repo,
        "bot": repo if repo != "shared" else "shared",
        "category": category,
        "purpose": purpose,
        "business_hypothesis": hypothesis,
        "status_state": status_state,
        "status_pct": status_pct,
        "operational_status": operational_status,
        "current_verdict": verdict,
        "owner": "mihai",
        "tags": tags,
        "notes": notes,
        "components": [
            {
                "component_name": n,
                "component_category": c,
                "description": d,
                "status_state": status_state,
                "notes": "",
            }
            for n, c, d in components
        ],
        "file_links": [
            {"repo": repo if repo != "shared" else f_repo, "file_path": path, "role": role, "is_shadow": shadow, "notes": ""}
            for f_repo, path, role in files
        ],
        "metrics": [
            {"metric_name": n, "target_value": tv, "threshold_rule": tr, "notes": ""}
            for n, tv, tr in metrics
        ],
        "rules": [
            {
                "rule_name": "default_verdict_rule",
                "rule_kind": "governance",
                "severity": "warn" if verdict in {"WATCH", "FREEZE"} else "block",
                "rule_config": {"verdict": verdict},
                "notes": "Seeded governance rule",
            }
        ],
        "watchlist": [
            {
                "metric_name": n,
                "trigger_rule": trig,
                "reevaluation_cadence": cadence,
                "trigger_action": action,
                "active": True,
                "notes": "",
            }
            for n, trig, cadence, action in watchlist
        ],
        "versions": versions
        or [
            {
                "version": "v1",
                "summary": "Seed import from current repo state",
                "reason_for_change": "Initial canonical registry migration",
                "metrics_before": {},
                "metrics_after": {},
                "decision": verdict,
                "files_changed": [path for _, path, _ in files],
            }
        ],
    }


SEED_STRATEGIES = [
    _strategy(
        id="breakout_setup",
        name="Breakout setup",
        repo="crypto-bot",
        category="setup",
        purpose="Capture strong continuation moves in favorable regime.",
        hypothesis="Breakout signals produce tradable edge when paired with regime/risk filters.",
        status_state="functional",
        status_pct=75,
        operational_status="active",
        verdict="WATCH",
        tags=["breakout", "entry", "setup", "trend"],
        files=[
            ("crypto-bot", r"D:\crypto-bot\core\ideas.py", "implementation"),
            ("crypto-bot", r"D:\crypto-bot\main.py", "runtime"),
            ("crypto-bot", r"D:\crypto-bot\paper_engine\runner.py", "paper-runtime"),
        ],
        components=[
            ("breakout_signal", "setup", "Entry signal generation"),
            ("breakout_replay", "validation_tooling", "Replay and backtest coverage"),
        ],
        metrics=[("profit_factor", ">=1.3", "promotion"), ("top3_share_pct", "<=70", "robustness")],
        watchlist=[("profit_factor", "PF < 1.3", "weekly", "TUNE"), ("top3_share_pct", "top3_share_pct > 70", "weekly", "FREEZE")],
    ),
    _strategy(
        id="pullback_setup",
        name="Pullback setup",
        repo="crypto-bot",
        category="setup",
        purpose="Enter retracements inside trend context.",
        hypothesis="Pullback entries improve fill quality but require cleaner context control.",
        status_state="partial",
        status_pct=50,
        operational_status="shadow",
        verdict="WATCH",
        tags=["pullback", "entry", "setup"],
        files=[
            ("crypto-bot", r"D:\crypto-bot\main.py", "runtime"),
            ("crypto-bot", r"D:\crypto-bot\core\ideas.py", "implementation"),
        ],
        components=[("pullback_signal", "setup", "Legacy pullback setup in runtime and idea layer")],
        metrics=[("trades_executed", ">=20", "sample-size"), ("max_drawdown_pct", ">=-15", "safety")],
        watchlist=[("shadow_logic", "duplicate pullback logic persists", "weekly", "AUDIT")],
        notes="Exists in multiple forms (`Pullback`, `PullbackV2`) and needs consolidation.",
        shadow=True,
    ),
    _strategy(
        id="pullback_v2_setup",
        name="Pullback V2 setup",
        repo="crypto-bot",
        category="setup",
        purpose="Refined pullback logic used by batch/paper paths.",
        hypothesis="A more explicit pullback variant may behave differently from legacy runtime pullback.",
        status_state="partial",
        status_pct=50,
        operational_status="supporting",
        verdict="WATCH",
        tags=["pullbackv2", "pullback", "paper-engine"],
        files=[
            ("crypto-bot", r"D:\crypto-bot\core\ideas.py", "implementation"),
            ("crypto-bot", r"D:\crypto-bot\paper_engine\config.py", "configuration"),
        ],
        components=[("pullback_v2", "setup", "Paper engine / batch-only pullback variant")],
        metrics=[("rows_after_filter", ">=40", "search-gate")],
        watchlist=[("alignment", "runtime and paper disagree", "weekly", "AUDIT")],
    ),
    _strategy(
        id="btc_regime_gate",
        name="BTC regime gate",
        repo="crypto-bot",
        category="regime_filter",
        purpose="Restrict scanning/execution to favorable BTC structural regimes.",
        hypothesis="Macro context filter should reduce poor-context entries and drawdown.",
        status_state="functional",
        status_pct=75,
        operational_status="active",
        verdict="KEEP",
        tags=["btc", "regime", "trend_strong", "filter"],
        files=[
            ("crypto-bot", r"D:\crypto-bot\core\regime_gate.py", "implementation"),
            ("crypto-bot", r"D:\crypto-bot\main.py", "runtime"),
            ("crypto-bot", r"D:\crypto-bot\scripts\regime_opportunity_report.py", "validation"),
        ],
        components=[("trend_strong_gate", "regime_filter", "Gate entire scan on BTC regime")],
        metrics=[("max_drawdown_pct", ">=-15", "safety"), ("rows_after_filter", ">=40", "density")],
        watchlist=[("rows_after_filter", "rows_after_filter < 40", "weekly", "WATCH")],
    ),
    _strategy(
        id="btc_risk_off_filter",
        name="BTC risk-off filter",
        repo="crypto-bot",
        category="regime_filter",
        purpose="Use BTC daily EMA200 risk-off logic to filter or constrain entries.",
        hypothesis="BTC risk-off state improves replay quality but may overfilter and concentrate edge.",
        status_state="functional",
        status_pct=75,
        operational_status="active",
        verdict="WATCH",
        tags=["btc", "risk_off", "ema200", "filter"],
        files=[
            ("crypto-bot", r"D:\crypto-bot\main.py", "runtime"),
            ("crypto-bot", r"D:\crypto-bot\scripts\portfolio_replay.py", "validation"),
            ("crypto-bot", r"D:\crypto-bot\scripts\phaseb_incremental.sh", "validation"),
        ],
        components=[("risk_off_gate", "regime_filter", "Per-run and replay BTC risk-off gating")],
        metrics=[("profit_factor", ">=1.3", "promotion"), ("top3_share_pct", "<=80", "concentration")],
        watchlist=[("top3_share_pct", "top3_share_pct > 80", "6h", "FREEZE"), ("profit_factor", "PF < 1.3", "6h", "TUNE")],
    ),
    _strategy(
        id="atr_quality_filter",
        name="ATR quality filter",
        repo="crypto-bot",
        category="quality_filter",
        purpose="Reject excessive volatility contexts via ATR caps.",
        hypothesis="ATR filtering can improve signal quality if it preserves enough density.",
        status_state="functional",
        status_pct=75,
        operational_status="active",
        verdict="WATCH",
        tags=["atr", "volatility", "quality", "max_atr"],
        files=[
            ("crypto-bot", r"D:\crypto-bot\scripts\portfolio_replay.py", "validation"),
            ("crypto-bot", r"D:\crypto-bot\scripts\micro_autoresearch.py", "research"),
        ],
        components=[("max_atr_filter", "quality_filter", "Replay-time ATR cap")],
        metrics=[("rows_after_filter", ">=40", "search-gate"), ("top3_share_pct", "<=70", "robustness")],
        watchlist=[("rows_after_filter", "rows_after_filter < 40", "weekly", "FREEZE")],
    ),
    _strategy(
        id="risk_per_trade_sizing",
        name="Risk-per-trade sizing",
        repo="crypto-bot",
        category="risk_sizing",
        purpose="Scale exposure per trade without changing signal logic.",
        hypothesis="Sizing should amplify valid edge, not create it.",
        status_state="complete",
        status_pct=100,
        operational_status="active",
        verdict="KEEP",
        tags=["sizing", "risk_per_trade", "exposure"],
        files=[
            ("crypto-bot", r"D:\crypto-bot\risk_manager.py", "implementation"),
            ("crypto-bot", r"D:\crypto-bot\scripts\portfolio_replay.py", "validation"),
        ],
        components=[("risk_per_trade", "risk_sizing", "Fixed fraction exposure per trade")],
        metrics=[("max_drawdown_pct", ">=-15", "safety")],
        watchlist=[("max_drawdown_pct", "max_drawdown_pct < -15", "weekly", "TUNE")],
    ),
    _strategy(
        id="cooldown_logic",
        name="Cooldown logic",
        repo="crypto-bot",
        category="risk_sizing",
        purpose="Reduce clustering and low-quality immediate re-entries.",
        hypothesis="Cooldown reduces repeated poor entries and concentration of losses.",
        status_state="partial",
        status_pct=50,
        operational_status="active",
        verdict="WATCH",
        tags=["cooldown", "reentry", "clustering"],
        files=[
            ("crypto-bot", r"D:\crypto-bot\main.py", "runtime"),
            ("crypto-bot", r"D:\crypto-bot\scripts\portfolio_replay.py", "validation"),
        ],
        components=[("symbol_cooldown", "risk_sizing", "Per-symbol cooldown after loss/exit")],
        metrics=[("max_losing_streak", "<=7", "safety")],
        watchlist=[("max_losing_streak", "max_losing_streak > 7", "weekly", "TUNE")],
    ),
    _strategy(
        id="max_positions_cap",
        name="Max positions cap",
        repo="crypto-bot",
        category="risk_sizing",
        purpose="Control portfolio overlap and diversify edge.",
        hypothesis="Max positions changes the distribution of captured opportunities and concentration.",
        status_state="partial",
        status_pct=50,
        operational_status="active",
        verdict="WATCH",
        tags=["max_positions", "portfolio", "overlap"],
        files=[
            ("crypto-bot", r"D:\crypto-bot\main.py", "runtime"),
            ("crypto-bot", r"D:\crypto-bot\scripts\portfolio_replay.py", "validation"),
        ],
        components=[("position_cap", "risk_sizing", "Concurrent positions cap")],
        metrics=[("top3_share_pct", "<=70", "robustness")],
        watchlist=[("top3_share_pct", "top3_share_pct > 70", "weekly", "WATCH")],
    ),
    _strategy(
        id="execution_cost_realism",
        name="Execution cost realism",
        repo="crypto-bot",
        category="execution_realism",
        purpose="Ensure edge survives fees and slippage.",
        hypothesis="Strategies without healthy breakeven buffer are fantasy.",
        status_state="complete",
        status_pct=100,
        operational_status="active",
        verdict="KEEP",
        tags=["cost", "slippage", "fees", "breakeven"],
        files=[
            ("crypto-bot", r"D:\crypto-bot\core\cost_model.py", "implementation"),
            ("crypto-bot", r"D:\crypto-bot\scripts\cost_sensitivity.py", "validation"),
        ],
        components=[("cost_sensitivity", "validation_tooling", "Breakeven cost analysis")],
        metrics=[("breakeven_bps", ">=80", "promotion")],
        watchlist=[("breakeven_bps", "breakeven_bps < 80", "6h", "FREEZE")],
    ),
    _strategy(
        id="concentration_check",
        name="Concentration check",
        repo="crypto-bot",
        category="validation_tooling",
        purpose="Reject fragile edge dominated by a few symbols or outlier trades.",
        hypothesis="Healthy edge should not be monopolized by a tiny subset of symbols/trades.",
        status_state="complete",
        status_pct=100,
        operational_status="active",
        verdict="KEEP",
        tags=["concentration", "top3", "outliers", "robustness"],
        files=[
            ("crypto-bot", r"D:\crypto-bot\scripts\concentration_check.py", "implementation"),
        ],
        components=[("top3_share", "validation_tooling", "Symbol concentration diagnostics")],
        metrics=[("top3_share_pct", "<=70", "promotion"), ("top5_trades_pct", "<=80", "watch")],
        watchlist=[("top3_share_pct", "top3_share_pct > 70", "6h", "FREEZE")],
    ),
    _strategy(
        id="validation_battery",
        name="Validation battery",
        repo="shared",
        category="validation_tooling",
        purpose="Run replay + cost + concentration batteries and emit structured verdicts.",
        hypothesis="Repeated, structured validation beats ad-hoc terminal interpretation.",
        status_state="functional",
        status_pct=75,
        operational_status="active",
        verdict="KEEP",
        tags=["validation_battery", "recipe_runner", "verdict"],
        files=[
            ("automation-mvp", r"D:\automation-mvp\recipe_runner.py", "implementation"),
            ("automation-mvp", r"D:\automation-mvp\recipes\crypto_phaseb_riskoff.json", "recipe"),
            ("automation-mvp", r"D:\automation-mvp\recipes\crypto_phaseb_rangechop.json", "recipe"),
        ],
        components=[("recipe_runner", "validation_tooling", "Sequential command runner with extractors/rules")],
        metrics=[("verdict", "PROMOTE/WARN/REJECT", "output")],
        watchlist=[("recipe_health", "recipe failures or stale metrics", "daily", "WATCH")],
    ),
    _strategy(
        id="micro_autoresearch",
        name="Micro autoresearch",
        repo="crypto-bot",
        category="validation_tooling",
        purpose="Run tiny offline sweeps to invalidate fragile parameter candidates quickly.",
        hypothesis="A microscopic search tool can expose false-positive parameter winners without touching core logic.",
        status_state="functional",
        status_pct=75,
        operational_status="active",
        verdict="WATCH",
        tags=["micro_autoresearch", "search", "offline", "sweep"],
        files=[
            ("crypto-bot", r"D:\crypto-bot\scripts\micro_autoresearch.py", "implementation"),
            ("crypto-bot", r"D:\crypto-bot\configs\search_space.yaml", "configuration"),
        ],
        components=[("search_space", "validation_tooling", "Small parameter grid"), ("hard_gates", "validation_tooling", "Reject small/concentrated samples")],
        metrics=[("trades_executed", ">=20", "gate"), ("rows_after_filter", ">=40", "gate"), ("top3_share_pct", "<=70", "gate")],
        watchlist=[("score", "no valid configs across runs", "weekly", "FREEZE")],
    ),
    _strategy(
        id="ml_risk_overlay",
        name="ML risk overlay",
        repo="crypto-bot",
        category="ml_overlay",
        purpose="Use ML as risk gate / size modifier rather than directional oracle.",
        hypothesis="ML can improve risk control if it reduces drawdown without emptying the flow.",
        status_state="partial",
        status_pct=50,
        operational_status="supporting",
        verdict="WATCH",
        tags=["ml", "overlay", "risk_gate", "p_highrisk"],
        files=[
            ("crypto-bot", r"D:\crypto-bot\core\ml_risk.py", "implementation"),
            ("crypto-bot", r"D:\crypto-bot\ml_gate.py", "shadow"),
            ("crypto-bot", r"D:\crypto-bot\ml_risk_gate.py", "shadow"),
        ],
        components=[("ml_risk_action", "ml_overlay", "ALLOW/HALF/SKIP path"), ("legacy_ml_gate", "shadow", "Old ML gate path")],
        metrics=[("max_drawdown_pct", "improve vs baseline", "promotion"), ("rows_after_filter", "not collapse", "promotion")],
        watchlist=[("duplicate_ml_logic", "legacy ml gates still active", "weekly", "AUDIT")],
        notes="Current state has overlapping ML paths and should be audited before expansion.",
        shadow=True,
    ),
    _strategy(
        id="legacy_decision_logging",
        name="Legacy decision logging overlap",
        repo="crypto-bot",
        category="observability",
        purpose="Track overlapping CSV and JSONL decision logs that may no longer be consistent.",
        hypothesis="Logging duplication creates drift and hides runtime truth.",
        status_state="shadow",
        status_pct=25,
        operational_status="shadow",
        verdict="REMOVE",
        tags=["logging", "decision_log", "shadow"],
        files=[
            ("crypto-bot", r"D:\crypto-bot\trade_logger.py", "implementation"),
            ("crypto-bot", r"D:\crypto-bot\core\decision_log.py", "implementation"),
            ("crypto-bot", r"D:\crypto-bot\ml_pipeline.py", "implementation"),
        ],
        components=[("csv_logging", "observability", "Legacy CSV journaling"), ("jsonl_logging", "observability", "Structured JSONL logging")],
        metrics=[("consistency", "single runtime truth", "audit")],
        watchlist=[("shadow_logging", "duplicate decision logs persist", "weekly", "REMOVE")],
        shadow=True,
    ),
    _strategy(
        id="sec_form4_ingest",
        name="SEC Form 4 ingest",
        repo="stocks-bot",
        category="signal_source",
        purpose="Build event-level insider transaction signals from Form 4 filings.",
        hypothesis="Reliable insider-event ingest is the base signal source for all downstream strategy layers.",
        status_state="functional",
        status_pct=75,
        operational_status="active",
        verdict="KEEP",
        tags=["sec", "form4", "ingest", "events"],
        files=[
            ("stocks-bot", r"D:\stocks-bot\src\ingest\build_events_job.py", "implementation"),
            ("stocks-bot", r"D:\stocks-bot\src\features\event_aggregates.py", "implementation"),
        ],
        components=[("event_build", "signal_source", "Form 4 -> issuer-day event layer")],
        metrics=[("coverage", "maintain", "operational"), ("freshness", "maintain", "operational")],
        watchlist=[("coverage", "coverage degrades materially", "weekly", "WATCH")],
    ),
    _strategy(
        id="event_candidate_stamp",
        name="Event candidate stamp",
        repo="stocks-bot",
        category="quality_filter",
        purpose="Tag upstream events as strategy candidates using config-driven filters.",
        hypothesis="Pre-stamping candidates reduces downstream noise while preserving cohort signal.",
        status_state="functional",
        status_pct=75,
        operational_status="active",
        verdict="KEEP",
        tags=["candidate", "omb", "roles", "strict_cluster"],
        files=[
            ("stocks-bot", r"D:\stocks-bot\src\ingest\build_events_job.py", "implementation"),
            ("stocks-bot", r"D:\stocks-bot\src\config.py", "configuration"),
        ],
        components=[("candidate_stamp", "quality_filter", "Config-driven event-level candidate flag")],
        metrics=[("candidate_count", "stable", "operational")],
        watchlist=[("candidate_count", "candidate count collapses", "weekly", "WATCH")],
    ),
    _strategy(
        id="generic_risk_gate",
        name="Generic risk gate",
        repo="stocks-bot",
        category="quality_filter",
        purpose="Apply rule-based risk rejection on liquidity, spread, price, and event features.",
        hypothesis="A generic risk gate provides a defensible baseline but may now be secondary to winner cohorts.",
        status_state="functional",
        status_pct=75,
        operational_status="supporting",
        verdict="WATCH",
        tags=["risk_gate", "liquidity", "spread", "baseline"],
        files=[
            ("stocks-bot", r"D:\stocks-bot\src\scoring\risk_gate.py", "implementation"),
        ],
        components=[("rule_risk_gate", "quality_filter", "Legacy baseline risk gate")],
        metrics=[("pass_rate", "explainable", "governance")],
        watchlist=[("relevance", "winner path bypasses gate", "monthly", "AUDIT")],
    ),
    _strategy(
        id="generic_ranker",
        name="Generic ranker",
        repo="stocks-bot",
        category="ranking",
        purpose="Rank generic insider ideas via rule-based scoring.",
        hypothesis="Rule-based ranking is useful as a baseline but must remain explainable and auditable.",
        status_state="functional",
        status_pct=75,
        operational_status="supporting",
        verdict="WATCH",
        tags=["ranker", "scoring", "ideas", "baseline"],
        files=[
            ("stocks-bot", r"D:\stocks-bot\src\scoring\ranker.py", "implementation"),
            ("stocks-bot", r"D:\stocks-bot\src\scoring\explain.py", "implementation"),
        ],
        components=[("ranker", "ranking", "Generic score/rank baseline")],
        metrics=[("precision", "improve vs baseline", "validation")],
        watchlist=[("explainability", "scoring cannot be explained", "monthly", "FREEZE")],
    ),
    _strategy(
        id="strategy_v1_runtime_filter",
        name="Strategy V1 runtime filter",
        repo="stocks-bot",
        category="runtime_filter",
        purpose="Operational paper-trading filter used by paper_job and related commands.",
        hypothesis="A simple runtime filter can support paper accounting even if research moves toward winner cohorts.",
        status_state="functional",
        status_pct=75,
        operational_status="active",
        verdict="WATCH",
        tags=["strategy_v1", "paper", "runtime"],
        files=[
            ("stocks-bot", r"D:\stocks-bot\src\strategy\strategy_v1.py", "implementation"),
            ("stocks-bot", r"D:\stocks-bot\src\strategy\paper_job.py", "runtime"),
        ],
        components=[("runtime_filter", "runtime_filter", "Paper-trading candidate filter")],
        metrics=[("candidate_count", "stable", "operational")],
        watchlist=[("alignment", "runtime filter diverges from canonical cohorts", "weekly", "AUDIT")],
    ),
    _strategy(
        id="c10_cohort",
        name="C10 winner cohort",
        repo="stocks-bot",
        category="winner_cohort",
        purpose="Primary operational candidate cohort for current paper validation.",
        hypothesis="Officer/director cohort with low OMB threshold provides better operational candidate quality.",
        status_state="functional",
        status_pct=75,
        operational_status="active",
        verdict="WATCH",
        tags=["c10", "winner", "cohort", "paper"],
        files=[
            ("stocks-bot", r"D:\stocks-bot\src\backtest\cohort_baseline.py", "validation"),
            ("stocks-bot", r"D:\stocks-bot\src\backtest\c10_candidate_audit.py", "validation"),
            ("stocks-bot", r"D:\stocks-bot\configs\canonical_profiles.yaml", "configuration"),
            ("stocks-bot", r"D:\stocks-bot\docs\WINNER_VERDICT.md", "decision-record"),
        ],
        components=[("c10_profile", "winner_cohort", "Officer/director canonical cohort"), ("paper_eval", "validation_tooling", "C10 paper eval path")],
        metrics=[("paper_eval_quality", "maintain", "promotion"), ("candidate_count", "maintain", "operational")],
        watchlist=[("paper_eval_quality", "paper candidate quality degrades", "weekly", "TUNE")],
    ),
    _strategy(
        id="b20_cohort",
        name="B20 winner cohort",
        repo="stocks-bot",
        category="winner_cohort",
        purpose="Backup/reference winner cohort compared against C10.",
        hypothesis="B20 may remain a valid benchmark even if not the primary operating profile.",
        status_state="functional",
        status_pct=75,
        operational_status="supporting",
        verdict="WATCH",
        tags=["b20", "winner", "cohort", "benchmark"],
        files=[
            ("stocks-bot", r"D:\stocks-bot\src\backtest\winner_sensitivity.py", "validation"),
            ("stocks-bot", r"D:\stocks-bot\configs\canonical_profiles.yaml", "configuration"),
        ],
        components=[("b20_profile", "winner_cohort", "Backup/reference cohort")],
        metrics=[("baseline_quality", "benchmark", "validation")],
        watchlist=[("benchmark_value", "no longer useful as benchmark", "monthly", "FREEZE")],
    ),
    _strategy(
        id="a20_reference",
        name="A20 premium reference",
        repo="stocks-bot",
        category="winner_cohort",
        purpose="Premium/reference cohort used as upper benchmark, not default operational target.",
        hypothesis="A20 serves as reference rather than the immediate practical profile.",
        status_state="functional",
        status_pct=75,
        operational_status="supporting",
        verdict="WATCH",
        tags=["a20", "premium", "benchmark"],
        files=[
            ("stocks-bot", r"D:\stocks-bot\configs\canonical_profiles.yaml", "configuration"),
            ("stocks-bot", r"D:\stocks-bot\docs\WINNER_VERDICT.md", "decision-record"),
        ],
        components=[("a20_reference", "winner_cohort", "Premium reference cohort")],
        metrics=[("benchmark_gap", "track vs c10", "validation")],
        watchlist=[("benchmark_gap", "A20 no longer informative", "monthly", "FREEZE")],
    ),
    _strategy(
        id="cohort_baseline_validation",
        name="Cohort baseline validation",
        repo="stocks-bot",
        category="validation_tooling",
        purpose="Validate winner cohorts under constrained equal-weight baselines.",
        hypothesis="Winner cohorts must outperform simple baselines to be meaningful.",
        status_state="functional",
        status_pct=75,
        operational_status="active",
        verdict="KEEP",
        tags=["cohort_baseline", "validation", "equal_weight"],
        files=[
            ("stocks-bot", r"D:\stocks-bot\src\backtest\cohort_baseline.py", "implementation"),
        ],
        components=[("baseline_eval", "validation_tooling", "Equal-weight cohort baseline validator")],
        metrics=[("20d_excess", "> baseline", "validation")],
        watchlist=[("20d_excess", "baseline edge disappears", "weekly", "FREEZE")],
    ),
    _strategy(
        id="winner_sensitivity_validation",
        name="Winner sensitivity validation",
        repo="stocks-bot",
        category="validation_tooling",
        purpose="Stress-test winner cohorts under slots/cost/candidate-cap variations.",
        hypothesis="Robust winner cohorts should survive realistic operational perturbations.",
        status_state="functional",
        status_pct=75,
        operational_status="active",
        verdict="KEEP",
        tags=["winner_sensitivity", "validation", "costs"],
        files=[
            ("stocks-bot", r"D:\stocks-bot\src\backtest\winner_sensitivity.py", "implementation"),
        ],
        components=[("sensitivity_grid", "validation_tooling", "Operational sensitivity sweeps")],
        metrics=[("cost_survival", "positive", "validation")],
        watchlist=[("cost_survival", "cost sensitivity degrades", "weekly", "TUNE")],
    ),
    _strategy(
        id="c10_candidate_audit",
        name="C10 candidate audit",
        repo="stocks-bot",
        category="validation_tooling",
        purpose="Audit operational candidate set for the current winner cohort.",
        hypothesis="Forward candidate audit is necessary before trusting paper/live promotion.",
        status_state="functional",
        status_pct=75,
        operational_status="active",
        verdict="KEEP",
        tags=["c10", "candidate_audit", "paper_eval"],
        files=[
            ("stocks-bot", r"D:\stocks-bot\src\backtest\c10_candidate_audit.py", "implementation"),
        ],
        components=[("candidate_audit", "validation_tooling", "Operational audit of winner cohort candidates")],
        metrics=[("candidate_quality", "stable", "validation")],
        watchlist=[("candidate_quality", "audit quality weakens", "weekly", "WATCH")],
    ),
    _strategy(
        id="paper_eval_accounting",
        name="Paper eval accounting",
        repo="stocks-bot",
        category="validation_tooling",
        purpose="Operational paper-style accounting engine for forward evaluation.",
        hypothesis="Accounting correctness is required before any forward result can be trusted.",
        status_state="functional",
        status_pct=75,
        operational_status="active",
        verdict="KEEP",
        tags=["paper_eval", "accounting", "forward"],
        files=[
            ("stocks-bot", r"D:\stocks-bot\src\strategy\paper_job.py", "implementation"),
            ("stocks-bot", r"D:\stocks-bot\tests\test_paper_eval_accounting.py", "test"),
        ],
        components=[("paper_accounting", "validation_tooling", "Forward paper accounting engine")],
        metrics=[("accounting_integrity", "pass", "validation")],
        watchlist=[("accounting_integrity", "paper accounting drift/failures", "weekly", "FREEZE")],
    ),
    _strategy(
        id="legacy_sim_eval_stack",
        name="Legacy ideas sim eval stack",
        repo="stocks-bot",
        category="validation_tooling",
        purpose="Older generic ideas -> sim -> eval pipeline kept as baseline/legacy path.",
        hypothesis="Legacy stack may remain useful as baseline but is no longer the canonical operating layer.",
        status_state="shadow",
        status_pct=25,
        operational_status="shadow",
        verdict="FREEZE",
        tags=["legacy", "ideas", "sim", "eval", "shadow"],
        files=[
            ("stocks-bot", r"D:\stocks-bot\src\sim\sim_job.py", "implementation"),
            ("stocks-bot", r"D:\stocks-bot\src\eval\eval_job.py", "implementation"),
            ("stocks-bot", r"D:\stocks-bot\src\ideas\idea_job.py", "implementation"),
        ],
        components=[("legacy_pipeline", "validation_tooling", "Older research path")],
        metrics=[("relevance", "baseline only", "audit")],
        watchlist=[("shadow_logic", "legacy stack still drives decisions", "monthly", "REMOVE")],
        shadow=True,
    ),
    _strategy(
        id="breakout_momentum",
        name="Breakout Momentum family",
        repo="crypto-bot",
        category="research_family",
        purpose="Month-1 research family for continuation breakouts on 4h Top-50 data.",
        hypothesis="Simple breakout continuation on 4h may survive costs if signal density and concentration are acceptable.",
        status_state="functional",
        status_pct=75,
        operational_status="research_active",
        verdict="WATCH",
        tags=["month1", "research", "breakout", "momentum", "4h"],
        files=[
            ("crypto-bot", "core/ideas.py", "implementation"),
            ("crypto-bot", "scripts/run_cohort_research.py", "orchestration"),
            ("crypto-bot", "configs/discovery_profiles_breakout_momentum.json", "configuration"),
            ("crypto-bot", "scripts/profile_discovery.py", "validation"),
        ],
        components=[("breakout_family", "research_family", "Continuation breakout hypothesis batch")],
        metrics=[("candidate_count", ">=1", "shadow-screen"), ("window_passes", ">=1", "shadow-screen"), ("top3_share_pct", "<=70", "robustness")],
        watchlist=[("candidate_count", "candidate_count < 1", "daily", "REJECT"), ("window_passes", "window_passes < 1", "daily", "WATCH")],
    ),
    _strategy(
        id="spike_mean_reversion",
        name="Spike Mean Reversion family",
        repo="crypto-bot",
        category="research_family",
        purpose="Month-1 research family for long mean reversion after downside 4h liquidation-like flushes.",
        hypothesis="Oversold high-volume downside spikes may mean-revert over the next 1-3 bars on 4h data.",
        status_state="functional",
        status_pct=75,
        operational_status="research_active",
        verdict="WATCH",
        tags=["month1", "research", "mean_reversion", "spike", "4h"],
        files=[
            ("crypto-bot", "core/ideas.py", "implementation"),
            ("crypto-bot", "scripts/run_cohort_research.py", "orchestration"),
            ("crypto-bot", "configs/discovery_profiles_spike_mean_reversion.json", "configuration"),
            ("crypto-bot", "scripts/profile_discovery.py", "validation"),
        ],
        components=[("spike_mr_family", "research_family", "Downside spike mean-reversion hypothesis batch")],
        metrics=[("candidate_count", ">=1", "shadow-screen"), ("window_passes", ">=1", "shadow-screen"), ("max_drawdown_pct", ">=-25", "early-screen")],
        watchlist=[("candidate_count", "candidate_count < 1", "daily", "REJECT"), ("window_passes", "window_passes < 1", "daily", "WATCH")],
    ),
    _strategy(
        id="cross_sectional_momentum",
        name="Cross-sectional Momentum family",
        repo="crypto-bot",
        category="research_family",
        purpose="Month-1 research family for ranking Top-50 coins by relative strength and replaying the strongest candidates.",
        hypothesis="Relative-strength leadership on 4h may persist long enough to produce repeatable edge when ranked cross-sectionally.",
        status_state="functional",
        status_pct=75,
        operational_status="research_active",
        verdict="WATCH",
        tags=["month1", "research", "cross_sectional", "momentum", "top50"],
        files=[
            ("crypto-bot", "scripts/generate_cross_sectional_batch.py", "implementation"),
            ("crypto-bot", "scripts/run_cohort_research.py", "orchestration"),
            ("crypto-bot", "configs/discovery_profiles_cross_sectional_momentum.json", "configuration"),
            ("crypto-bot", "scripts/profile_discovery.py", "validation"),
        ],
        components=[("xsmom_family", "research_family", "Cross-sectional momentum hypothesis batch")],
        metrics=[("candidate_count", ">=1", "shadow-screen"), ("window_passes", ">=1", "shadow-screen"), ("top3_share_pct", "<=70", "robustness")],
        watchlist=[("candidate_count", "candidate_count < 1", "daily", "REJECT"), ("window_passes", "window_passes < 1", "daily", "WATCH")],
    ),
]
